### ISSUE TITLE
Decode error when set AVCodecID as `AV_CODEC_ID_ADPCM_MS`

### ISSUE THREAD

**Issue by qiujiandong** [pschatzmann/adpcm#2]
Hi, first of all —— this is a wonderful job! I also tried to extract ADPCM codec code from FFmpeg but failed. 

The test program use `AV_CODEC_ID_ADPCM_IMA_WAV` as the default AVCodecID, it seems correct because the decode output is also Sine wave.

But when I use `AV_CODEC_ID_ADPCM_MS` as the AVCodecID, the decode output becomes all zero.

I find out that when using `AV_CODEC_ID_ADPCM_MS` the decode output is in `frame.data`, but not `frame.extended_data`. I don't known the detail of the algorithm, so I don't known how to fix it. Please help me!

Here is the code let me feel confused. It replace the `frame.data` with `frame.extended_data`

```c
int16_t *result16 = (int16_t *)frame.data[0];
int pos = 0;
for (int j = 0; j < frame.nb_samples; j++) {
  for (int ch = 0; ch < avctx.nb_channels; ch++) {
    result16[pos++] = frame.extended_data[ch][j];
  }
}
```

**Comment by pschatzmann** [comment]
I can reproduce your issue: Fortunately we can build and debug this on the desktop...

**Comment by pschatzmann** [comment]
I committed a correction: test test is now poviding some result for the  AV_CODEC_ID_ADPCM_MS as well.

**Comment by pschatzmann** [comment]
Taking my statement back: I noticed that setting the DEBUG flag is only activating AV_CODEC_ID_ADPCM_IMA_WAV independently of the setting...

**Comment by pschatzmann** [comment]
This is really ugly: It seems that there are two ways that the result is returned.
I committed a correction that should handle both cases by checking which one contains values

**Comment by qiujiandong** [comment]
@pschatzmann Thank you so much for your help!
